### ISSUE TITLE
List of categories + emojis 

### ISSUE THREAD

**Issue by MaxKaay** [deora-earth/solarpunch#1]
# Bounty
Let's identify the categories that cover a set of processes inside an organisations. To make it more accessible we can make us of emojis for certain interactions within an organisation. Allowing the user to visually understand processes easier. 
e.g.
- payments
- communication (Chat, Thread, 
- 

## Scope
- list view of process categories 
- explanation of category and their possible subcategories 
- emojis that are useful for certain interactions

## Deliverables
- list of categories and emojis that can be used respectively for a certain "action"  inside an organisation 

## Gain for the project
Curated content needs a curation with a filter method. This allows users to easily find their most needed solutions.

## Roles
bounty gardener: @MaxKuck   / 10%  
bounty worker: @MaxKuck / 75% 
bounty reviewer: name / share

**Comment by MaxKaay** [comment]
See also here for categories: https://forms.gle/zDhgf2GALdftvF1W9

**Comment by simonweniger** [comment]
created by @MaxKuck  [Categorie list](https://hackmd.io/i45pVVkTS-aMAvb8TCCItQ)

**Comment by MaxKaay** [comment]
finished here: https://www.figma.com/file/YBtu9So2RtqtmWVmurFH9d/SOLARPUNCH?node-id=0%3A1
review required @cyan-one ?

**Comment by simonweniger** [comment]
followed your process live all the time and the result is great! But we still need one emoji for automation right ? @MaxKuck

**Comment by simonweniger** [comment]
maybe we use the gear emoji

**Comment by MaxKaay** [comment]
yeah, I'd love to use a positive looking bot (not like the one from figmoji) ... a gear could also be a solution but a bit "boring"/colourless .
