### ISSUE TITLE
Think about Naming 

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/solarpunch#10]
# Bounty
As we come close to the development of Solarpunch, we have to start thinking about branding. That we can communicate the site easy and people remember it through a catchy name!

**Is the final product called Solarpunch ? Is it called Deora ? Do we come up with a new name ?** 

Someone should take care of this and manage the name finding.

## Scope
- Manage naming ideas in a list
- collect Name ideas from team members
- push the naming stuff forward

## Deliverables
- Name for the final product 

## Gain for the project
- catchy name that people can remember and know what it is.

## Roles
bounty gardener: @cyan-one  / 10%  
bounty worker: @zschavi  / 80%
bounty reviewer: daily Standup  / 10%

**Comment by ghost** [comment]
https://docs.google.com/spreadsheets/d/19Qx23ojxz6YOG36vWwg0oysHYeVwrN5yc-lW93TSqow/edit?usp=sharing
