### ISSUE TITLE
Think about Voting & Token

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/solarpunch#12]
# Bounty
We already discussed the idea of a potential token to give users an incentive system and the possibility to vote on prozesses via a web3 Solution. To come this goal closer someone should think about how we can integrate it.

## Scope
- Think about a Token (token bonding curve)
- Come up with a plan for implementation)

## Deliverables
- a document that explains the idea & the plan

## Gain for the project
- possiblity to integrate web3 feauters

## Roles
bounty gardener: @cyan-one  / 10%  
bounty worker: @johannbarbie / 80%  
bounty reviewer: @zschavi  / 10%

**Comment by johba37** [comment]
results described here: https://hackmd.io/7m7vSEg9Q9yce9wBOlxEiA

next steps:
- start simple by web3 provider.
- add universal.login or burner core.
- maybe add token economy with quadratic betting.
