### ISSUE TITLE
create CI / CD for staging environment

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/solarpunch#16]
# Bounty
Since the about site is almost ready and the development for the site is starting this week. We need CI / CD for the repo

> tealgarden.deora.earth
## Scope
- build on all branches
- ~deploy to staging on all but develop branches~

## Deliverables
- s3 bucket for staging
- cloudfront distribution for staging
- domain configuration for staging
- ssl configuration for staging

## Gain for the project
smooth development process

## Roles
bounty gardener: @cyan-one  / 10%  
bounty worker: @johannbarbie  / 80%  
bounty reviewer: name / share

**Comment by johba37** [comment]
- [x] [build on all branches](https://github.com/deora-earth/solarpunch/blob/master/.travis.yml)
- [] ~deploy to staging on all but develop branches~

## Deliverables
- [x] [s3 bucket for staging](https://console.aws.amazon.com/s3/buckets/tealgarden.deora.earth/?region=eu-central-1)
- [x] [cloudfront distribution for staging](https://console.aws.amazon.com/cloudfront/home?#distribution-settings:E3SNJRNXHFND2O)
- [x] [domain configuration for staging](https://console.aws.amazon.com/route53/home#resource-record-sets:Z04501662KD1L042IX49J)
- [x] [ssl configuration for staging](https://console.aws.amazon.com/acm/home?region=us-east-1#/?id=arn:aws:acm:us-east-1:716291991285:certificate%2F822933e4-1492-4db3-820b-4bc4dd8a1f73)

**Comment by johba37** [comment]
https://tealgarden.deora.earth/
