### ISSUE TITLE
buy the domain teal.garden

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/solarpunch#18]
# Bounty
We discussed in the daily standup and in the deora tactical to focus on the main branding deora and communicate everything as deora. The Main page should be hosted on teal.deora.earth but it would be grate to also have the site teal.garden with a redirect. Therfore someone has to buy the domain and request a reimbursement by the deora multisig

## Scope
- buy the domain

## Deliverables
- the domain teal.garden

## Gain for the project
nice user experiance and good for SEO

## Roles
bounty gardener: @cyan-one  / 10%  
bounty worker: name / share  
bounty reviewer: name / share

**Comment by Clearwood** [comment]
bought the domain :)
