### ISSUE TITLE
Sample processes of deora / LeapDAO organisation

### ISSUE THREAD

**Issue by MaxKaay** [deora-earth/solarpunch#2]
# Bounty
Let's visualize and summarize our processes as a tests that will be displayed on the website. 
This can go hand-in-hand with issue #3 

## Scope
- visualize processes of LeapDAO and deora 
- short explanatory text for each process

## Deliverables
- drawing of processes and explanation

## Gain for the project
Better understanding of the SolarPunch user

## Roles
bounty gardener: @MaxKuck  / share  
bounty worker: @MaxKuck  / share  
bounty reviewer: @cyan-one  / share

**Comment by MaxKaay** [comment]
work in progress: https://docs.google.com/drawings/d/1lpCLaqLzlyJlb7XahD1Ur8JHzFS3qQeC5CYWFqRh_5M/edit?usp=sharing

**Comment by MaxKaay** [comment]
as a video: https://we.tl/t-C6HXnr4HAs

**Comment by MaxKaay** [comment]
dogfood feedback:
- framework is needed (what is needed to say, to write)
- emoticons needed
- time marker for the video as in "tl;dv" with titles (github, bounty set-up etc.) 
- description also with minute feature to add the exact minutes
- normal process view looks suuper boring. we need some nice and fun gaming style of process view
- screen capture can be super individual and not seen as a modular basis of tools and process used (people loose the scope/overview of the process presented)

**Comment by simonweniger** [comment]
Layout inspirationen aus den daily standup

![mautic-zapier-zap-actions](https://user-images.githubusercontent.com/43147663/76845146-aee92f00-683e-11ea-9965-8f13be306c9b.jpg)

![Bildschirmfoto 2020-03-17 um 11 00 38](https://user-images.githubusercontent.com/43147663/76845155-b577a680-683e-11ea-9eba-88e0f01c4127.png)

**Comment by MaxKaay** [comment]
@cyan-one Updated: https://www.figma.com/file/0IR4mgKRsnUpx8sGH46tHu/Solarpunch-Process-View-0.5?node-id=0%3A1
