### ISSUE TITLE
Setup an email / newsletter system (PP)

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/solarpunch#20]
# Bounty

We setup an open source email/newsletter system to inform the community about our teal efforts. Which tool is useful to: catch all emails (signup widget) + list management & segmentation of audiences + batch send to contacts

## Scope
- find a tool which can serve all features we desire.
- make sure we can send batches of mails easily & decentralized (self-hosted)
- setup & integration of the tool

## Deliverables
- research and decide on tool via vote in slack
- host & setup, enabling first check on interface via localhost

## Gain for the project
Setup an self hosted email client, put learnings into a process for tealgarden

## Roles
bounty gardener: @cyan-one / 10%  
bounty worker: @zschavi @johannbarbie / 80%  
bounty reviewer: name / share

**Comment by zschavi** [comment]
we need the following features:

**List Management**
* we need to add subscribers manually, through API or import from a CSV file
* we need lists with support for custom fields and merge tags.

**Custom Fields**
* Text fields, numbers, drop downs or checkboxes for users to provide information.
* custom fields should be usable with merge tags

**List Segmentation**
* we need segments in the list: to send emails only to list subscribers that match predefined segmentation rules.

**Click Stats**
* for each campaign, we need the individual click statistics for every link included in the message

**Template Editors**
* best: code editor to build our own HTML

**Automation**
* we define triggers, once a users triggers them, they get an email.
e.g. Welcome mail, confirmation mails or unsubscribe mails.

**Comment by zschavi** [comment]
first wave of research brings the following tools to surface:

**1. listmonk**
https://listmonk.app/
https://github.com/knadh/listmonk

**2. Mailtrain**
https://mailtrain.org/
https://github.com/Mailtrain-org/mailtrain

**Comment by ghost** [comment]
https://hackmd.io/2mu3qM3PTF-WxLLqqDRTSQ?view

progress made.
research done.
once tool is chosen,
we move on to:

* host & setup, enabling first check on interface via localhost

**Comment by johba37** [comment]
listmonk instance is configured here: https://lightmonk.deora.earth/
@zschavi has access credential

**Comment by simonweniger** [comment]
reviewd. I got an email and subscribed to the list 
![Bildschirmfoto 2020-04-13 um 12 45 28](https://user-images.githubusercontent.com/43147663/79114859-a8d66780-7d84-11ea-9f80-ee85a513a9e2.png)
