### ISSUE TITLE
Setup Open Source Analytics tool (PP)

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/solarpunch#21]
# Bounty
The website is live and ready for their first hungry user. To see who, why and how they are visiting we need a tracking tool that matches our values

- [matomo](https://matomo.org/matomo-on-premise/)
- [openwebanalytics](http://www.openwebanalytics.com/)
- [countly](https://count.ly/pricing)

## Scope
- Check the tools and find the best
- set it up

## Deliverables
- working tracking tool, maybe a PR

## Gain for the project
good data analytics

## Roles
bounty gardener: @cyan-one / 10% 
bounty worker: @johannbarbie @cyan-one  / 80%  
bounty reviewer: name / 10%

**Comment by johba37** [comment]
[matomo minimum requirements](https://matomo.org/docs/requirements/#tracking-100000-page-views-per-month-or-less) exceed current [AWS free tier](https://aws.amazon.com/ec2/pricing/) that we have in deora.

**Comment by simonweniger** [comment]
@johannbarbie discoverd that we cant use an open source tool with our free AWS tier. For the reason see commen above.

I created a new property in our google analytics account (simon@deora.earth) And installed it in the react app.

**Comment by simonweniger** [comment]
solved with #26
