### ISSUE TITLE
integrate email list into landing page

### ISSUE THREAD

**Issue by johba37** [deora-earth/solarpunch#27]
# Bounty

here is the form that listmonk proposes:
```
<form method="post" action="https://lightmonk.deora.earth/subscription/form" class="listmonk-form">
    <div>
        <h3>Subscribe</h3>
        <p><input type="text" name="email" placeholder="E-mail" /></p>
        <p><input type="text" name="name" placeholder="Name (optional)" /></p>
        <p>
            <input type="checkbox" name="l" value="1b91ae57-2db7-4eda-973f-c32a0837a222" id="1b91a" />
            <label for="1b91a">Opt-in list</label>
        </p>
        <p><input type="submit" value="Subscribe" /></p>
    </div>
</form>
```

## Scope
- integrate into react app

## Deliverables
- working subscription on button click

## Gain for the project
- ability to collect emails

## Roles
bounty gardener: @zschavi  / share  
bounty worker: @cyan-one  / share  
bounty reviewer: name / share

**Comment by simonweniger** [comment]
@zschavi proposing **350 rep points** for this. Had to do a pretty big style work arround. To overwrite the list monk style 

<img width="714" alt="Bildschirmfoto 2020-04-15 um 03 21 18" src="https://user-images.githubusercontent.com/43147663/79288867-2e166500-7ec8-11ea-9c72-cacd4c474e26.png">
