### ISSUE TITLE
Design process view

### ISSUE THREAD

**Issue by MaxKaay** [deora-earth/solarpunch#3]
# Bounty
The process visualization is a central USP of SolarPunch. The central questions still is: How do we want to make the process visualization on the website look like? Let's find some ideas and first sketches.

## Scope
- conceptualise drawings of organisational processes
- acknowledge tech. limitations 
- define possible features of the process view

## Deliverables
- mockups and process drawings
- explanation text of features

## Roles
bounty gardener: @MaxKuck  / -  
bounty worker: @MaxKuck  / 90%  
bounty reviewer: @cyan-one / 10%

**Comment by simonweniger** [comment]
Deliverd by @MaxKuck with this one: https://www.figma.com/file/0IR4mgKRsnUpx8sGH46tHu/Solarpunch-Process-View-0.5?node-id=0%3A1
