### ISSUE TITLE
Define content for "About" page 

### ISSUE THREAD

**Issue by MaxKaay** [deora-earth/solarpunch#4]
# Bounty
Outlining information about SolarPunch and the importance of existence. We should present the bigger picture of individual and sovereign organisation processes.

## Scope
- conceptualise text content describing solarpunch 
- SolarPunch roadmap and desired feature list
- give outlook of Habitat as the bigger goal
- solarpunk movement description

## Roles
bounty gardener: @MaxKuck  / share  
bounty worker: name / share  
bounty reviewer: name / share

**Comment by ghost** [comment]
https://hackmd.io/v-w1P2CXRmeGzh4yPDZCTg?both

**Comment by ghost** [comment]
Last chapter about Solarpunk Movement upcoming :)

*edit:*
replace through a explainer of "teal" organizations ?

Solarpunk can be linked elsewhere, but does not relate too much to the "teal.garden"

**Comment by MaxKaay** [comment]
Review here: https://github.com/deora-earth/tealgarden/pull/19#issuecomment-611459019

**Comment by simonweniger** [comment]
done by @zschavi  with #19
