### ISSUE TITLE
Create first json scheme

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/solarpunch#44]
# Bounty
To test the implementation with gatsby and graphQL we have to create a Json scheme out of the our process drafts. 

## Scope
- create a first json scheme
- add it to the data repo

## Deliverables
PR

## Roles
bounty gardener: @cyan-one  / -  
bounty worker: @johannbarbie  / 90%  
bounty reviewer: @cyan-one  / 10%

**Comment by johba37** [comment]
done here: https://github.com/deora-earth/tealgarden/blob/develop/processSchema.json
