### ISSUE TITLE
Review Pull Requests

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/solarpunch#45]
# Bounty
We have some PR's ready for review. Someone (@johannbarbie ) should check them.

## Scope

- [x] give #40  a review
- [x] give #38 a review
- [x] give #32 a review

## Deliverables
Review on the PR's

## Gain for the project
good code quality

## Roles
bounty gardener: @cyan-one  / -  
bounty worker: @johannbarbie  / 100%  
bounty reviewer: @cyan-one  / -

**Comment by johba37** [comment]
- [x] reviews done
- [x] remaining issues [forked out](https://github.com/deora-earth/tealgarden/issues/47)
- [x] rebased all remaining PRs onto `develop` branch
