### ISSUE TITLE
create support material for tealgarden track at EthTurin

### ISSUE THREAD

**Issue by johba37** [deora-earth/solarpunch#49]
# Bounty

Hackers on the EthTurin - Teal.Garden track will need to know what to do.
Create support material to enable them to make great submissions.

We need basic explainers & an updated repo readme.

## Scope
- Why teal and holacracy?
- help them to fill out all parts of the process schema:
  - what is a process?
    - what is a component?
      - what is a role? (with and without context of holacracy)
      - what is a policy?
      - what is a domain?
    - what is an adoptionRequirement?
    - what is an instruction or tool?
 - what is up with these colors?

## Deliverables
- knowledgebase as browsable document
- updated readme.md in github repo to guide attendees of hackathon

## Gain for the project
knowledgebase as browsable document: explainers, later teal.garden faq?
## Roles
bounty gardener: @johannbarbie  / share  
bounty worker: @zschavi  / share  
bounty reviewer: name / share

**Comment by ghost** [comment]
* [x] Why teal and holacracy?
__
* [x] what is a process?
* [x] what is a component?
__
what is a role?
* [x] with context of holacracy
* [x] without context of holacracy
__
* [x] what is a policy?
* [x] what is a domain?
__
* [x] what is an adoptionRequirement?
* [x] what is an instruction or tool?

__bonus:__
* [x] what is up with these colors?

**Comment by ghost** [comment]
Explainers: https://hackmd.io/R0EIa_W1QZ2xVa0tSJqk6Q?both

Updated readme.md: https://github.com/deora-earth/tealgarden/blob/develop/README.md

ready for review

**Comment by johba37** [comment]
i've created a PR here, so comments and improvements can be added: https://github.com/deora-earth/tealgarden/pull/57

**Comment by IlluminatedUnicorn** [comment]
@johannbarbie Are you reviewing this as well?

**Comment by johba37** [comment]
yes, i've done a review here: https://github.com/deora-earth/tealgarden/pull/57
