### ISSUE TITLE
Define Deora Track @EthTurin (Pair Programming)

### ISSUE THREAD

**Issue by ghost** [deora-earth/solarpunch#53]
# Bounty

We sponsor ETHTurin & can define a track, we also define the prizes.
Let's define what hackers need to do, and want they get from us :)

## Scope
- create the track structure for ETH Turin
- define prize structure
- share with organizers

## Deliverables
* send track suggestion to matteo
* doc with all details & prizes

## Gain for the project
* Let hackers build processes to share on teal.garden
* Learn: Do people get what we want ?

## Roles
bounty gardener/worker: @zschavi  - 50%
bounty worker/reviewer: @johannbarbie - 50%

**Comment by ghost** [comment]
https://hackmd.io/sY3Fs1E6Qc6uJcwl4-OB4g

**Comment by johba37** [comment]
delivered here: https://github.com/deora-earth/tealgarden/pull/57
