### ISSUE TITLE
finalize mockups 

### ISSUE THREAD

**Issue by MaxKaay** [deora-earth/solarpunch#6]
# Bounty
For easier deployment we need a detailed mockup of the website including all sub-pages and functions. 

## Scope
- mockup design 
- feature definition
- "clickdummy" (understanding of user flow)

## Deliverables
- mockup design of the solurpunch website

## Gain for the project
Final visualization and understanding of dev scope

## Roles
bounty gardener: @MaxKuck  / 10%  
bounty worker: @cyan-one  / 90%  
bounty reviewer: daily standup / -

**Comment by simonweniger** [comment]
### **To dos in the [SolraPunch figma file](https://www.figma.com/file/YBtu9So2RtqtmWVmurFH9d/prozesshunt?node-id=0%3A1)** 
- [x] finalize categorie page
- [x] design about page
- [x] design publish new page
- [x] create prototype 
- [x] final mockups, second go through -> finalization
- [x] create handover file for the development

**Comment by simonweniger** [comment]
@MaxKuck can you resize it to an XL ?

**Comment by simonweniger** [comment]
solved with this one: [Final clickdummy](https://www.figma.com/proto/YBtu9So2RtqtmWVmurFH9d/SOLARPUNCH?node-id=156%3A0&viewport=385%2C-1166%2C0.1821906715631485&scaling=min-zoom)
